# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docenteAsignaturaPeriodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docenteasignaturaperiodo',
            unique_together=set([('asignatura', 'periodo')]),
        ),
    ]
