# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.SmallIntegerField()),
                ('tema', models.TextField(max_length=256)),
                ('fecha', models.DateField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Horario')),
            ],
        ),
    ]
