# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('0', 'Sin Revisar'), ('1', 'Aprobado'), ('2', 'No Aprobado')], default='0', max_length=1)),
                ('comentario', models.TextField(max_length=256, null=True)),
                ('aprobar_otra_fecha', models.BooleanField(default=False)),
                ('revisado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Unidad'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='tema',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planificacion.Tema'),
        ),
        migrations.AlterUniqueTogether(
            name='planificacion',
            unique_together=set([('tema', 'fecha')]),
        ),
    ]
