# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tema',
            name='unidad',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planificacion.Unidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planificacion',
            name='tema',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
