# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_auto_20160711_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
    ]
