# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_auto_20160712_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='comentario',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
