# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_auto_20160712_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='horario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='horario.Horario'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='unidad',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='planificacion.Unidad'),
        ),
    ]
