# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_auto_20160712_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='tema',
            name='razon_aprobar_otra_fecha',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
