# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docenteAsignaturaPeriodoEstudiante', '0002_docenteasignaturaperiodoestudiante_idestudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docenteasignaturaperiodoestudiante',
            old_name='iddocenteasignatura',
            new_name='docenteasignatura',
        ),
        migrations.RenameField(
            model_name='docenteasignaturaperiodoestudiante',
            old_name='idestudiante',
            new_name='estudiante',
        ),
    ]
