# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.SmallIntegerField()),
                ('tema', models.TextField(max_length=256)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('0', 'Sin Revisar'), ('1', 'Aprobado'), ('2', 'No Aprobado')], default='0', max_length=1)),
                ('comentario', models.CharField(max_length=255)),
            ],
        ),
    ]
