# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictado', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictado',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Horario'),
        ),
    ]
