# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('dictado', '0002_dictado_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictado',
            name='revisado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
    ]
