# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictado', '0004_auto_20160605_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
