# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.TextField(max_length=256)),
                ('abierta', models.BooleanField()),
            ],
        ),
    ]
