# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docenteAsignaturaNivelPeriodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miercoles'), ('3', 'Jueves'), ('4', 'Viernes')], default='0', max_length=1)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docenteAsignaturaNivelPeriodo.DocenteAsignaturaNivelPeriodo')),
            ],
        ),
    ]
