# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_auto_20160801_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fin',
            field=models.CharField(choices=[('07:30', '07:30'), ('08:30', '08:30'), ('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30')], default='09:30', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='inicio',
            field=models.CharField(choices=[('07:30', '07:30'), ('08:30', '08:30'), ('09:30', '09:30'), ('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30')], default='07:30', max_length=5),
        ),
    ]
