# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0004_auto_20160801_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fin',
            field=models.CharField(choices=[('1', '1 Hora'), ('2', '2 Horas')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='horario',
            name='inicio',
            field=models.CharField(choices=[('1', '07:30'), ('2', '09:30'), ('3', '11:30'), ('4', '14:30')], default='1', max_length=1),
        ),
    ]
